boost:
  - 1.88

# only for local build ? see https://github.com/conda/conda-build/issues/4064#issuecomment-702983257
#CONDA_BUILD_SYSROOT:
#  - /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
